"""What may be reclaimed under training_outputs/, and what must never be.

The disk problem is real: every full run writes per-epoch checkpoints, and a
checkpoint of a quantised 3B model with optimizer state dwarfs the 47 MB adapter
anyone wants. After a term, most of `training_outputs/` is checkpoints for
adapters that already exist.

The risk is equally real and much worse in one direction. A deleted checkpoint
costs the ability to resume a finished run. A deleted adapter costs a model that
cannot be recreated without another GPU allocation, and for a course being
served, without students noticing first. So every test here that matters is
about something being protected.
"""

from __future__ import annotations

import json
import sys
import unittest
from importlib.machinery import SourceFileLoader
from pathlib import Path
from tempfile import TemporaryDirectory

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts" / "lib"))

import retention  # noqa: E402
import training_state  # noqa: E402

apply_retention_plan = SourceFileLoader(
    "apply_retention_plan", str(REPO_ROOT / "scripts" / "lib" / "apply_retention_plan.py")
).load_module()

CSS350 = "css-350-spring-2026-n3h9"
CSS360 = "css-360-winter-2026-a7rp"


class RetentionTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.repo_root = Path(self.tmp.name) / "repo"
        self.repo_root.mkdir(parents=True)
        self.outputs = Path(self.tmp.name) / "training_outputs"
        self.serving = self.outputs / "serving"

    def write_run(
        self,
        course_id: str,
        stamp: str,
        mode: str = "full",
        *,
        complete: bool = True,
        checkpoints: bool = True,
        adapter: bool = True,
        queue_run_id: str | None = None,
    ) -> Path:
        run_dir = self.outputs / "qlora-runs" / course_id / f"{stamp}-{mode}"
        run_dir.mkdir(parents=True, exist_ok=True)

        if complete:
            (run_dir / "runtime-report.json").write_text(
                json.dumps({"mode": mode, "completedSteps": 15}), encoding="utf-8"
            )
        if adapter:
            adapter_dir = run_dir / "adapter"
            adapter_dir.mkdir(exist_ok=True)
            (adapter_dir / "adapter_config.json").write_text("{}", encoding="utf-8")
            (adapter_dir / "adapter_model.safetensors").write_bytes(b"w" * 100)
        if checkpoints:
            checkpoint_dir = run_dir / "checkpoints" / "checkpoint-15"
            checkpoint_dir.mkdir(parents=True, exist_ok=True)
            (checkpoint_dir / "optimizer.pt").write_bytes(b"x" * 5000)
        if queue_run_id:
            (run_dir / "run-meta.env").write_text(
                f"COURSE_ID={course_id}\nQUEUE_RUN_ID={queue_run_id}\n", encoding="utf-8"
            )
        return run_dir

    def publish(self, course_id: str, version: str, source_ref: str) -> None:
        course_dir = self.serving / course_id
        adapter = course_dir / version / "adapter"
        adapter.mkdir(parents=True, exist_ok=True)
        (adapter / "adapter_config.json").write_text("{}", encoding="utf-8")
        (adapter / "adapter_model.safetensors").write_bytes(b"w" * 100)
        (course_dir / "current.json").write_text(
            json.dumps(
                {"courseId": course_id, "version": version, "sourceRef": source_ref}
            ),
            encoding="utf-8",
        )

    def plan(self, **kwargs) -> dict:
        return retention.plan_reclaimable(
            self.outputs, repo_root=self.repo_root, **kwargs
        )

    def candidate_paths(self, plan: dict) -> list:
        return [item["path"] for item in plan["candidates"]]


class CandidateTests(RetentionTestCase):
    def test_checkpoints_of_a_completed_full_run_are_reclaimable(self) -> None:
        run = self.write_run(CSS350, "20260827T064701Z")

        plan = self.plan()

        self.assertIn(str(run / "checkpoints"), self.candidate_paths(plan))
        self.assertGreater(plan["reclaimableBytes"], 0)

    def test_the_adapter_of_that_same_run_is_never_a_candidate(self) -> None:
        """The line the whole script exists to hold.

        Checkpoints and the adapter live side by side in one run directory, and
        only one of them can be regenerated by rerunning anything.
        """
        run = self.write_run(CSS350, "20260827T064701Z")

        paths = self.candidate_paths(self.plan())

        self.assertNotIn(str(run / "adapter"), paths)
        self.assertNotIn(str(run), paths)

    def test_a_smoke_run_is_reclaimable_whole(self) -> None:
        run = self.write_run(CSS350, "20260826T120000Z", mode="smoke")

        plan = self.plan()

        self.assertIn(str(run), self.candidate_paths(plan))

    def test_smoke_runs_can_be_kept_as_well(self) -> None:
        run = self.write_run(CSS350, "20260826T120000Z", mode="smoke")

        plan = self.plan(include_smoke=False)

        self.assertNotIn(str(run), self.candidate_paths(plan))

    def test_an_empty_outputs_root_plans_nothing(self) -> None:
        plan = self.plan()

        self.assertEqual(plan["candidates"], [])
        self.assertEqual(plan["reclaimableBytes"], 0)


class ProtectionTests(RetentionTestCase):
    def test_a_run_a_published_adapter_came_from_is_protected(self) -> None:
        """A model students are being served must keep its provenance.

        `current.json` records the run its adapter was copied from, so that run
        is off limits even though the served copy lives elsewhere.
        """
        run = self.write_run(CSS350, "20260827T064701Z")
        self.publish(
            CSS350,
            "v1",
            f"qlora-runs/{CSS350}/20260827T064701Z-full/adapter",
        )

        plan = self.plan()

        self.assertNotIn(str(run / "checkpoints"), self.candidate_paths(plan))
        reasons = {item["path"]: item["reason"] for item in plan["protected"]}
        self.assertIn("published course adapter", reasons[str(run)])

    def test_a_published_smoke_run_is_protected_too(self) -> None:
        run = self.write_run(CSS350, "20260826T120000Z", mode="smoke")
        self.publish(
            CSS350, "v1", f"qlora-runs/{CSS350}/20260826T120000Z-smoke/adapter"
        )

        self.assertNotIn(str(run), self.candidate_paths(self.plan()))

    def test_the_serving_tree_is_never_walked_for_candidates(self) -> None:
        """Nothing under serving/ is proposed, by construction.

        The planner only ever descends into `qlora-runs/`, and the deletion gate
        refuses any path containing a protected directory name regardless.
        """
        self.write_run(CSS350, "20260827T064701Z")
        self.publish(CSS350, "v1", "qlora-runs/other/run-full/adapter")

        paths = self.candidate_paths(self.plan())

        self.assertFalse([path for path in paths if "/serving/" in path])

    def test_a_run_still_owing_a_report_is_protected(self) -> None:
        """Its output is the evidence for something the application does not know.

        Deleting it while a completion is still queued would remove exactly what
        the pending report describes.
        """
        run = self.write_run(
            CSS350, "20260827T064701Z", queue_run_id="run-20260827t064701z-1cf650"
        )
        training_state.queue_pending_callback(
            self.repo_root,
            run_id="run-20260827t064701z-1cf650",
            course_id=CSS350,
            kind="completed",
            payload={"outcome": "succeeded"},
        )

        plan = self.plan()

        self.assertNotIn(str(run / "checkpoints"), self.candidate_paths(plan))
        reasons = {item["path"]: item["reason"] for item in plan["protected"]}
        self.assertIn("owes the application a report", reasons[str(run)])

    def test_a_run_with_an_unreported_submission_is_protected(self) -> None:
        run = self.write_run(
            CSS350, "20260827T064701Z", queue_run_id="run-20260827t064701z-1cf650"
        )
        training_state.write_run_record(
            self.repo_root,
            run_id="run-20260827t064701z-1cf650",
            course_id=CSS350,
            mode="full",
            job_id="264787",
            reported=False,
        )

        self.assertNotIn(str(run / "checkpoints"), self.candidate_paths(self.plan()))

    def test_an_unfinished_run_is_protected(self) -> None:
        """No runtime report means still running, or died. Neither is a candidate."""
        run = self.write_run(CSS350, "20260827T064701Z", complete=False)

        plan = self.plan()

        self.assertNotIn(str(run / "checkpoints"), self.candidate_paths(plan))
        reasons = {item["path"]: item["reason"] for item in plan["protected"]}
        self.assertIn("no runtime report", reasons[str(run)])

    def test_an_unrecognised_directory_is_left_alone(self) -> None:
        stray = self.outputs / "qlora-runs" / CSS350 / "notes"
        stray.mkdir(parents=True)
        (stray / "readme.txt").write_text("keep me", encoding="utf-8")

        plan = self.plan()

        self.assertEqual(plan["candidates"], [])
        self.assertIn(str(stray), [item["path"] for item in plan["protected"]])

    def test_one_courses_cleanup_never_reaches_another(self) -> None:
        css350 = self.write_run(CSS350, "20260827T064701Z")
        css360 = self.write_run(CSS360, "20260820T100000Z")
        self.publish(CSS360, "v1", f"qlora-runs/{CSS360}/20260820T100000Z-full/adapter")

        paths = self.candidate_paths(self.plan())

        self.assertIn(str(css350 / "checkpoints"), paths)
        self.assertNotIn(str(css360 / "checkpoints"), paths)


class DeletionGateTests(RetentionTestCase):
    def test_a_checkpoints_directory_passes_the_gate(self) -> None:
        run = self.write_run(CSS350, "20260827T064701Z")

        self.assertTrue(
            retention.is_deletion_safe(run / "checkpoints", self.outputs)
        )

    def test_an_adapter_directory_never_passes(self) -> None:
        run = self.write_run(CSS350, "20260827T064701Z")

        self.assertFalse(retention.is_deletion_safe(run / "adapter", self.outputs))

    def test_anything_under_serving_never_passes(self) -> None:
        self.publish(CSS350, "v1", "qlora-runs/x/y-full/adapter")

        self.assertFalse(
            retention.is_deletion_safe(self.serving / CSS350 / "v1", self.outputs)
        )
        self.assertFalse(retention.is_deletion_safe(self.serving, self.outputs))

    def test_a_backup_directory_never_passes(self) -> None:
        backup = self.outputs / "adapter-backups" / "20260827T000000Z"
        backup.mkdir(parents=True)

        self.assertFalse(retention.is_deletion_safe(backup, self.outputs))

    def test_a_full_run_directory_itself_never_passes(self) -> None:
        run = self.write_run(CSS350, "20260827T064701Z")

        self.assertFalse(retention.is_deletion_safe(run, self.outputs))

    def test_a_smoke_run_directory_passes(self) -> None:
        run = self.write_run(CSS350, "20260826T120000Z", mode="smoke")

        self.assertTrue(retention.is_deletion_safe(run, self.outputs))

    def test_the_outputs_root_itself_never_passes(self) -> None:
        self.outputs.mkdir(parents=True, exist_ok=True)

        self.assertFalse(retention.is_deletion_safe(self.outputs, self.outputs))

    def test_a_path_outside_the_outputs_root_never_passes(self) -> None:
        outside = Path(self.tmp.name) / "elsewhere" / "checkpoints"
        outside.mkdir(parents=True)

        self.assertFalse(retention.is_deletion_safe(outside, self.outputs))


class ApplyTests(RetentionTestCase):
    def test_applying_removes_exactly_the_planned_paths(self) -> None:
        run = self.write_run(CSS350, "20260827T064701Z")
        plan = self.plan()
        removed: list = []

        result = apply_retention_plan.apply_plan(
            plan,
            self.outputs,
            retention=retention,
            remove=lambda path: removed.append(str(path)),
        )

        self.assertEqual(removed, [str(run / "checkpoints")])
        self.assertEqual(result["removed"], [str(run / "checkpoints")])
        self.assertTrue((run / "adapter").is_dir())

    def test_a_path_that_became_unsafe_since_the_plan_is_skipped(self) -> None:
        """The gate is re-checked at deletion time, not trusted from the plan.

        A plan can be printed, read, and acted on minutes later. In between,
        somebody may have published an adapter from a run that was a candidate.
        """
        plan = {
            "candidates": [
                {"path": str(self.serving / CSS350 / "v1"), "bytes": 100},
            ]
        }

        result = apply_retention_plan.apply_plan(
            plan, self.outputs, retention=retention, remove=lambda path: None
        )

        self.assertEqual(result["removed"], [])
        self.assertEqual(len(result["skipped"]), 1)
        self.assertIn("no longer safe", result["skipped"][0]["reason"])

    def test_an_already_deleted_path_is_not_an_error(self) -> None:
        run = self.write_run(CSS350, "20260827T064701Z")
        plan = self.plan()
        import shutil

        shutil.rmtree(run / "checkpoints")

        result = apply_retention_plan.apply_plan(
            plan, self.outputs, retention=retention, remove=lambda path: None
        )

        self.assertEqual(result["removed"], [])
        self.assertEqual(result["skipped"][0]["reason"], "already gone")

    def test_applying_a_real_plan_frees_the_checkpoints_only(self) -> None:
        run = self.write_run(CSS350, "20260827T064701Z")
        plan = self.plan()

        apply_retention_plan.apply_plan(plan, self.outputs, retention=retention)

        self.assertFalse((run / "checkpoints").exists())
        self.assertTrue((run / "adapter" / "adapter_model.safetensors").is_file())
        self.assertTrue((run / "runtime-report.json").is_file())


if __name__ == "__main__":
    unittest.main()
