"""Fine-Tuned + RAG: course retrieval + remote LoRA inference.

Reuses course-specific retrieval from ``course_rag`` and the existing
fine-tuned HTTP client. Does not change Base, RAG, or Fine-Tuned paths.

The one optional input, ``model_version``, is the administrator's model-testing
override: an explicitly named version checked against the registry instead of
the version the registry chooses. Retrieval, the grounded prompt and the client
call are the same either way, which is what makes a test answer representative
of a classroom one. Without it the path is exactly as it was.
"""

from __future__ import annotations

from typing import Any

from fastapi import HTTPException

from app.course_id import assert_valid_course_id
from app.course_model_resolution import (
    resolve_course_model_version,
    resolve_current_course_model,
)
from app.course_rag import retrieve_course_syllabus_chunks
from app.finetuned_client import generate_finetuned_response
from app.retrieval_diversity import DEFAULT_TOP_K
from app.storage import CourseArtifactStorage


def _validate_course_id(course_id: str) -> str:
    try:
        return assert_valid_course_id(course_id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


def build_finetuned_rag_prompt(
    question: str,
    retrieved_chunks: list[dict[str, Any]],
) -> str:
    """Build a grounded prompt for the fine-tuned model with syllabus context."""
    context_blocks: list[str] = []
    source_sections: list[str] = []

    for chunk in retrieved_chunks:
        section = str(chunk["section"])
        text = str(chunk["text"])
        source_sections.append(section)
        context_blocks.append(f"[Section: {section}]\n{text}")

    unique_sections = list(dict.fromkeys(source_sections))
    section_list = "\n".join(f"- {section}" for section in unique_sections)
    context_text = "\n\n".join(context_blocks)

    return (
        "You are answering a student question about a course syllabus.\n\n"
        "The syllabus excerpts below are the factual source of truth.\n\n"
        "Rules:\n"
        "- Answer only from the supplied syllabus context.\n"
        "- Do not invent policies, dates, percentages, locations, or requirements.\n"
        "- Do not use general knowledge to fill gaps.\n"
        "- Treat the supplied context as the only factual source of truth.\n"
        "- If the context does not support the answer, say that the syllabus "
        "context provided does not contain enough information.\n"
        "- Preserve exact numbers, dates, times, percentages, and deadlines "
        "exactly as written in the context.\n"
        "- Keep the answer concise and student-friendly.\n"
        "- Do not mention that the answer was generated by AI.\n"
        "- Write natural student-facing prose. Do not mention internal labels "
        "such as Section:, Excerpt, or Retrieved context.\n\n"
        f"Student question:\n{question.strip()}\n\n"
        "Syllabus context:\n"
        f"{context_text}\n\n"
        "Source sections:\n"
        f"{section_list}\n\n"
        "Answer the student question now:"
    )


def _sources_from_chunks(retrieved_chunks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        {
            "chunkId": chunk["chunk_id"],
            "sectionTitle": chunk["section"],
            "text": chunk["text"],
            "score": chunk["score"],
        }
        for chunk in retrieved_chunks
    ]


def _retrieved_payload(retrieved_chunks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        {
            "chunkId": chunk["chunk_id"],
            "section": chunk["section"],
            "text": chunk["text"],
            "score": chunk["score"],
        }
        for chunk in retrieved_chunks
    ]


async def generate_course_finetuned_rag_answer(
    course_id: str,
    question: str,
    top_k: int = DEFAULT_TOP_K,
    storage: CourseArtifactStorage | None = None,
    *,
    model_version: str | None = None,
) -> dict[str, Any]:
    """Retrieve course syllabus chunks, then generate with the fine-tuned service.

    `model_version` names the version to answer from instead of resolving the
    course's own. Only the administrator-only model-testing route passes it;
    the classroom route never does, and with it absent nothing here differs.
    """
    safe_course_id = _validate_course_id(course_id)
    trimmed = question.strip()
    if not trimmed:
        raise HTTPException(status_code=422, detail="Question must not be empty.")

    _, retrieved_chunks = await retrieve_course_syllabus_chunks(
        course_id=safe_course_id,
        question=trimmed,
        top_k=top_k,
        storage=storage,
    )

    if not retrieved_chunks:
        raise HTTPException(
            status_code=404,
            detail=(
                f'No usable syllabus context was retrieved for course "{safe_course_id}". '
                "Cannot generate a Fine-Tuned + RAG answer without retrieved context."
            ),
        )

    prompt = build_finetuned_rag_prompt(trimmed, retrieved_chunks)
    # The same course resolution the plain fine-tuned path does. Retrieval is
    # already course-scoped; without this the grounded prompt would be answered
    # by whichever adapter the service happened to have, which is the one way
    # this path could still cross courses. An explicitly named version goes
    # through the registry too — registered for this course, ready — rather
    # than straight to the service.
    if model_version is None:
        resolved = resolve_current_course_model(safe_course_id)
    else:
        resolved = resolve_course_model_version(safe_course_id, model_version)
    generation = await generate_finetuned_response(
        prompt,
        course_id=safe_course_id,
        model_version=resolved["version"],
    )

    return {
        "courseId": safe_course_id,
        "answer": generation["answer"],
        "model": generation["model"],
        "modelVersion": generation.get("model_version") or resolved["version"],
        "adapterLoaded": generation["adapter_loaded"],
        "generationSeconds": generation["generation_seconds"],
        "sources": _sources_from_chunks(retrieved_chunks),
        "retrievedChunks": _retrieved_payload(retrieved_chunks),
        "responseType": "fineTunedRag",
    }
