#!/usr/bin/env python3
"""Switch classroom generation between the VM (normal) and a Tillicum GPU (classroom GPU mode).

    ./scripts/classroom_gpu_mode.sh start --course css360e-autumn-2026-c08m --admin-email you@uw.edu
    ./scripts/classroom_gpu_mode.sh status [--verify --admin-email you@uw.edu]
    ./scripts/classroom_gpu_mode.sh stop  --course css360e-autumn-2026-c08m --admin-email you@uw.edu [--cancel-job]

What a mode is: one JSON file the backend reads before every generation
(`backend/app/generation_mode.py`). In GPU mode all four conditions are
generated by the Tillicum service through an SSH tunnel on 127.0.0.1:9101;
retrieval, prompts, the queue, auth and the database stay on the VM. The VM
services keep running in GPU mode, so switching back is immediate.

`start` changes nothing until every check has passed, and puts the VM mode
back itself if a check after the switch fails:

  1. the backend is up, runs code that knows about modes, and is in VM mode;
  2. the course's activated version, from the backend's registry;
  3. the Tillicum serving session (recorded by start_finetuned_service.sh);
  4. the tunnel (UW Duo prompt, interactive, never stored);
  5. the GPU service: healthy, CUDA, enough time left, the course and version
     published, decoding identical to production;
  6. a direct probe: Base and course answers with the classroom cap, the same
     prompt token count the VM's Ollama computes for the same question;
  7. switch (one atomic file write), then the backend reports GPU mode;
  8. all four conditions through the backend, each proven to have been
     answered on the GPU (response model + the service's own counters).

`stop` switches back first (one file write), then proves the VM path: models
warmed, all four conditions answered on the VM. Then it closes the tunnel and
cancels the Tillicum job (`--cancel-job`) or reminds you it is still running.

Prompts: the admin password (or AISWE_VERIFY_PASSWORD) and UW Duo. Nothing is
stored. No answer text is printed.
"""

from __future__ import annotations

import argparse
import datetime as dt
import importlib.util
import json
import os
import shlex
import subprocess
import sys
import tempfile
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND = REPO_ROOT / "backend"
LIB = REPO_ROOT / "scripts" / "lib"
SERVICE_DIR = REPO_ROOT / "training" / "inference_service"

if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


checks = _load("finetuned_production_checks", LIB / "finetuned_production_checks.py")
local_helpers = _load("finetuned_local_helpers", LIB / "finetuned_local_helpers.py")
service_helpers = _load("tillicum_service_helpers", SERVICE_DIR / "helpers.py")

# The backend's own rules, so the script and the backend cannot disagree about
# what a mode file means or what "production decoding" is.
from app import generation_mode as gm  # noqa: E402
from app.gpu_generation import check_decoding, expected_decoding  # noqa: E402
from app.grounded_generation import CLASSROOM_NUM_PREDICT, classroom_options  # noqa: E402
from fastapi import HTTPException  # noqa: E402

CONDITIONS = ("base", "rag", "fineTuned", "fineTunedRag")
DEFAULT_GPU_PORT = 9101
DEFAULT_REMOTE_PORT = 8001
DEFAULT_MIN_MINUTES = 60
PROBE_QUESTION = "When does the course meet?"
GPU_MARK = "(Tillicum GPU)"
STATE_ROOT = Path(os.environ.get("XDG_STATE_HOME") or Path.home() / ".local" / "state") / "css360-syllabus-bot"
FINETUNED_ENV = Path(os.environ.get("AISWE_FINETUNED_ENV") or Path.home() / ".config" / "aiswe" / "finetuned.env")


class Abort(Exception):
    """A check failed; the message says which and what to do."""


def say(status: str, message: str) -> None:
    print(f"{status:<5} {message}", flush=True)


# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #


@dataclass
class Config:
    backend_url: str = checks.DEFAULT_BACKEND_URL
    gpu_port: int = DEFAULT_GPU_PORT
    tillicum_login: str = field(default_factory=lambda: f"{os.environ.get('USER', 'user')}@tillicum.hyak.uw.edu")
    ollama_url: str = "http://127.0.0.1:11434"
    finetuned_url: str = "http://127.0.0.1:9001"
    timeout: float = 180.0

    @property
    def gpu_url(self) -> str:
        return f"http://127.0.0.1:{self.gpu_port}"

    @property
    def control_path(self) -> Path:
        return STATE_ROOT / "ssh-gpu-mode.sock"

    @property
    def tunnel_state(self) -> Path:
        return STATE_ROOT / "gpu-mode-tunnel.json"


# --------------------------------------------------------------------------- #
# Mode file
# --------------------------------------------------------------------------- #


def read_mode_file() -> tuple[Path, str | None, Any]:
    """(path, raw text or None, parsed GenerationMode or the error string)."""
    path = gm.mode_file_path()
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return path, None, gm.VM_MODE
    except OSError as exc:
        return path, None, f"cannot read: {exc}"
    try:
        return path, text, gm.parse_mode(text)
    except ValueError as exc:
        return path, text, f"invalid ({exc})"


def write_mode_file(content: dict[str, Any] | str) -> Path:
    """Atomic: the backend reads either the old file or the new one, never half."""
    path = gm.mode_file_path()
    text = content if isinstance(content, str) else json.dumps(content, indent=2) + "\n"
    if not isinstance(content, str):
        gm.parse_mode(text)  # never write something the backend would ignore
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".generation-mode.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.chmod(tmp, 0o600)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    return path


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


# --------------------------------------------------------------------------- #
# HTTP
# --------------------------------------------------------------------------- #


def get_json(transport: Any, url: str, *, timeout: float = 10.0) -> dict[str, Any] | None:
    result = transport.request("GET", url, timeout=timeout)
    return result.body if result.ok and isinstance(result.body, dict) else None


def post_json(transport: Any, url: str, body: dict[str, Any], *, timeout: float) -> Any:
    return transport.request("POST", url, body=body, timeout=timeout)


# --------------------------------------------------------------------------- #
# Tunnel
# --------------------------------------------------------------------------- #


def ssh_base(cfg: Config) -> list[str]:
    return ["ssh", "-o", f"ControlPath={cfg.control_path}"]


def tunnel_alive(cfg: Config, run: Callable = subprocess.run) -> bool:
    if not cfg.control_path.exists():
        return False
    result = run(ssh_base(cfg) + ["-O", "check", cfg.tillicum_login], capture_output=True, text=True)
    return result.returncode == 0


def read_tunnel_state(cfg: Config) -> dict[str, Any]:
    try:
        data = json.loads(cfg.tunnel_state.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (OSError, ValueError):
        return {}


def open_tunnel(cfg: Config, node: str, remote_port: int, run: Callable = subprocess.run) -> None:
    STATE_ROOT.mkdir(parents=True, exist_ok=True)
    print(f"      Opening the tunnel 127.0.0.1:{cfg.gpu_port} -> {node}:{remote_port} via {cfg.tillicum_login}.")
    print("      Complete UW password / Duo if prompted.", flush=True)
    result = run(
        ["ssh", "-f", "-N",
         "-o", "ControlMaster=yes", "-o", f"ControlPath={cfg.control_path}", "-o", "ControlPersist=yes",
         "-o", "ExitOnForwardFailure=yes", "-o", "ServerAliveInterval=30", "-o", "ServerAliveCountMax=3",
         "-L", f"127.0.0.1:{cfg.gpu_port}:{node}:{remote_port}", cfg.tillicum_login],
    )
    if result.returncode != 0:
        raise Abort("SSH tunnel failed (authentication cancelled, network, or the port forward was refused).")
    cfg.tunnel_state.write_text(
        json.dumps({"node": node, "remotePort": remote_port, "localPort": cfg.gpu_port,
                    "login": cfg.tillicum_login, "openedAt": now_iso()}) + "\n",
        encoding="utf-8",
    )


def close_tunnel(cfg: Config, run: Callable = subprocess.run) -> bool:
    closed = False
    if cfg.control_path.exists():
        result = run(ssh_base(cfg) + ["-O", "exit", cfg.tillicum_login], capture_output=True, text=True)
        closed = result.returncode == 0
    cfg.control_path.unlink(missing_ok=True)
    cfg.tunnel_state.unlink(missing_ok=True)
    return closed


def cancel_job(cfg: Config, job_id: str, run: Callable = subprocess.run) -> bool:
    """`scancel` through the tunnel's already-authenticated connection."""
    if not job_id.isdigit():
        return False
    result = run(ssh_base(cfg) + [cfg.tillicum_login, "scancel", job_id], capture_output=True, text=True)
    return result.returncode == 0


# --------------------------------------------------------------------------- #
# Checks
# --------------------------------------------------------------------------- #


def serving_session(run: Callable = subprocess.run) -> dict[str, Any]:
    """The session start_finetuned_service.sh recorded: node, port, job, expiry."""
    result = run(
        [sys.executable, str(REPO_ROOT / "training" / "serving_session.py"), "show", "--json"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise Abort(
            "No serving session found. Start the GPU job on Tillicum first "
            "(./training/start_finetuned_service.sh), or pass --node/--remote-port. "
            + (result.stderr or "").strip()[:300]
        )
    try:
        session = json.loads(result.stdout)
    except ValueError as exc:
        raise Abort(f"serving_session.py returned invalid JSON: {exc}") from exc
    if not session.get("node"):
        raise Abort("The recorded serving session names no compute node.")
    return session


def activated_version(session: Any, course_id: str) -> str:
    """The version the backend serves this course from: online and ready, highest."""
    result = session.get(f"/api/db/courses/{course_id}/model")
    if not result.ok or not isinstance(result.body, dict):
        raise Abort(f"Could not read the model registry for {course_id} (HTTP {result.status}).")
    versions = result.body.get("versions") or {}
    online = sorted(
        (v for v, record in versions.items()
         if isinstance(record, dict) and record.get("deployment") == "online" and record.get("status") == "ready"),
        key=lambda v: int(v[1:]) if v[1:].isdigit() else 0,
    )
    if not online:
        raise Abort(f"{course_id} has no activated model version. Activate one in Admin -> Models first.")
    return online[-1]


def gpu_health_problems(health: dict[str, Any] | None, *, course_id: str, version: str, min_minutes: float) -> list[str]:
    if health is None:
        return ["the GPU service did not answer /health through the tunnel"]
    problems: list[str] = []
    if health.get("status") != "ok" or health.get("adapterLoaded") is not True:
        problems.append(f"status={health.get('status')!r} (base model not loaded yet?)")
    if health.get("cudaAvailable") is not True:
        problems.append("CUDA is not available on the node")
    if "base" not in (health.get("targets") or []):
        problems.append("this build cannot answer Base/RAG (no 'base' target): update the service on Tillicum")
    try:
        check_decoding(health.get("decoding"), expected_decoding(max_new_tokens=None))
    except HTTPException as exc:
        problems.append(str(exc.detail))
    remaining = health.get("secondsRemaining")
    if isinstance(remaining, (int, float)) and remaining < min_minutes * 60:
        problems.append(f"only {remaining / 60:.0f} min left on the allocation (need {min_minutes:.0f}; --min-minutes)")
    course = next((c for c in health.get("courses") or [] if c.get("courseId") == course_id), None)
    if course is None:
        problems.append(f"{course_id} is not published on Tillicum (promote_qlora_adapter.sh)")
    elif version not in (course.get("versions") or []):
        problems.append(f"{course_id} {version} is not published on Tillicum (published: {course.get('versions')})")
    return problems


def vm_prompt_tokens(transport: Any, ollama_url: str, model: str, question: str, timeout: float) -> int | None:
    """Prompt tokens the VM's Ollama computes for one user message (1 token generated)."""
    result = post_json(transport, f"{ollama_url}/api/chat", {
        "model": model, "messages": [{"role": "user", "content": question}], "stream": False,
        "options": {**classroom_options(), "num_predict": 1},
    }, timeout=timeout)
    if result.ok and isinstance(result.body, dict) and isinstance(result.body.get("prompt_eval_count"), int):
        return result.body["prompt_eval_count"]
    return None


def probe_gpu(transport: Any, cfg: Config, *, course_id: str, version: str, base_model: str) -> list[str]:
    """Direct Base and course answers on the GPU, held to the classroom settings."""
    problems: list[str] = []
    for target, body in (
        ("base", {"question": PROBE_QUESTION, "target": "base", "maxNewTokens": CLASSROOM_NUM_PREDICT}),
        ("course", {"question": PROBE_QUESTION, "courseId": course_id, "modelVersion": version,
                    "maxNewTokens": CLASSROOM_NUM_PREDICT}),
    ):
        result = post_json(transport, f"{cfg.gpu_url}/generate", body, timeout=cfg.timeout)
        data = result.body if isinstance(result.body, dict) else {}
        if not result.ok:
            problems.append(f"{target}: HTTP {result.status} {str(data.get('detail') or result.error or '')[:200]}")
            continue
        try:
            check_decoding(data.get("decoding"), expected_decoding(max_new_tokens=CLASSROOM_NUM_PREDICT))
        except HTTPException as exc:
            problems.append(f"{target}: {exc.detail}")
        if data.get("target") != target:
            problems.append(f"{target}: answered as target {data.get('target')!r}")
        if target == "course" and (data.get("courseId"), data.get("modelVersion")) != (course_id, version):
            problems.append(f"course: answered for {data.get('courseId')}@{data.get('modelVersion')}")
        timings = data.get("timings") or {}
        if int(timings.get("output_tokens") or 0) > CLASSROOM_NUM_PREDICT:
            problems.append(f"{target}: {timings.get('output_tokens')} output tokens > cap {CLASSROOM_NUM_PREDICT}")
        if not str(data.get("answer") or "").strip():
            problems.append(f"{target}: empty answer")
        say("INFO", f"GPU {target}: {timings.get('output_tokens', '?')} tokens in {data.get('generationSeconds', 0):.1f}s")
        if target == "base":
            vm_tokens = vm_prompt_tokens(transport, cfg.ollama_url, base_model, PROBE_QUESTION, cfg.timeout)
            gpu_tokens = timings.get("prompt_tokens")
            if vm_tokens is None:
                say("WARN", "could not ask the VM's Ollama for its prompt token count; tokenisation parity not checked")
            elif vm_tokens != gpu_tokens:
                problems.append(f"prompt tokens differ from the VM's Ollama ({gpu_tokens} vs {vm_tokens}): prompt format mismatch")
            else:
                say("PASS", f"prompt tokenised identically to the VM's Ollama ({vm_tokens} tokens)")
    return problems


def run_four(session: Any, course_id: str, timeout: float) -> dict[str, Any]:
    """The Compare page's four requests, sequentially, sharing one comparison id."""
    comparison = f"gpu-mode-{uuid.uuid4().hex[:12]}"
    out: dict[str, Any] = {}
    for condition in CONDITIONS:
        result = checks.generate(session, condition, course_id, question=PROBE_QUESTION, timeout=timeout,
                                 comparison_id=comparison)
        out[condition] = result
    return out


def four_condition_problems(results: dict[str, Any], *, on_gpu: bool, course_id: str, version: str) -> list[str]:
    problems: list[str] = []
    for condition, result in results.items():
        body = result.body if isinstance(result.body, dict) else {}
        if not result.ok:
            detail = body.get("detail")
            problems.append(f"{condition}: HTTP {result.status} {str(detail or result.error or '')[:200]}")
            continue
        model = str(body.get("model") or "")
        answered_on_gpu = GPU_MARK in model
        if answered_on_gpu != on_gpu:
            problems.append(f"{condition}: answered by {model!r}, expected {'the GPU' if on_gpu else 'the VM'}")
        if condition in ("fineTuned", "fineTunedRag") and body.get("modelVersion") != version:
            problems.append(f"{condition}: version {body.get('modelVersion')!r}, expected {version}")
        if on_gpu and condition in ("fineTuned", "fineTunedRag") and f"{course_id}@{version}" not in model:
            problems.append(f"{condition}: not answered by {course_id}@{version} ({model!r})")
        say("INFO", f"{condition:12} {result.seconds:5.1f}s  {len(str(body.get('answer') or ''))} chars  {model}")
    return problems


def backend_mode(session: Any) -> dict[str, Any]:
    result = session.get("/api/admin/generation-mode")
    if not result.ok or not isinstance(result.body, dict):
        raise Abort(
            f"GET /api/admin/generation-mode failed (HTTP {result.status}). Is the backend running code that "
            "includes classroom GPU mode? (git pull, then systemctl --user restart aiswe-backend)"
        )
    return result.body


def sign_in(cfg: Config, email: str | None, transport: Any, *, no_auth: bool = False) -> Any:
    if no_auth:
        # scripts/classroom_load_harness.py only: it answers as an administrator.
        return checks.BackendSession(cfg.backend_url, transport, timeout=cfg.timeout)
    credentials = checks.resolve_admin_credentials(email)
    if credentials is None:
        raise Abort("An administrator sign-in is needed: --admin-email and the password (prompt or AISWE_VERIFY_PASSWORD).")
    session = checks.BackendSession(cfg.backend_url, transport, timeout=cfg.timeout)
    login = session.login(*credentials)
    if not login.ok or not session.signed_in:
        raise Abort(f"Sign-in failed (HTTP {login.status}).")
    return session


def vm_model_names(course_id: str, version: str) -> tuple[str, str | None, str]:
    """(base model, the course's VM Ollama tag, the fine-tuned service's Ollama URL)."""
    base = (os.environ.get("OLLAMA_MODEL") or "llama3.2:3b").strip()
    try:
        values = local_helpers.parse_env_file(FINETUNED_ENV.read_text(encoding="utf-8"))
    except OSError:
        values = {}
    try:
        mapping = service_helpers.parse_model_map(values.get(service_helpers.MODEL_MAP_ENV))
    except service_helpers.CourseAdapterError:
        mapping = {}
    tag = mapping.get(course_id, {}).get(version)
    return base, tag, (values.get("OLLAMA_BASE_URL") or "http://127.0.0.1:11434").rstrip("/")


# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #


def cmd_start(args: argparse.Namespace, cfg: Config, transport: Any) -> int:
    print("Classroom GPU mode: start. Nothing changes until every check below passes.\n")
    if not get_json(transport, f"{cfg.backend_url}/api/health"):
        raise Abort(f"The backend at {cfg.backend_url} is not answering /api/health.")
    session = sign_in(cfg, args.admin_email, transport, no_auth=args.no_auth)
    try:
        mode = backend_mode(session)
        if mode.get("mode") == gm.GPU:
            raise Abort("The backend is already in GPU mode. Use `status`, or `stop` first.")
        if mode.get("error"):
            raise Abort(f"The current mode file is unreadable ({mode['error']}); fix or remove it first.")
        say("PASS", "backend up, in VM mode")

        version = args.version or activated_version(session, args.course)
        say("PASS", f"{args.course}: version {version}" + (" (--version)" if args.version else " (activated in the backend)"))

        if args.node:
            node, remote_port, job_id, expires = args.node, args.remote_port, args.job_id or "", ""
        else:
            info = serving_session()
            node, remote_port = str(info["node"]), int(info.get("port") or DEFAULT_REMOTE_PORT)
            job_id, expires = str(info.get("jobId") or ""), str(info.get("expiresAt") or "")
        node = local_helpers_validate_node(node)
        say("PASS", f"Tillicum session: job {job_id or '?'} on {node}:{remote_port}, ends {expires or 'unknown'}")

        opened = False
        state = read_tunnel_state(cfg)
        if args.no_tunnel:
            if not get_json(transport, f"{cfg.gpu_url}/health"):
                raise Abort(f"--no-tunnel, but nothing answers {cfg.gpu_url}/health")
            say("PASS", f"using the existing forward on {cfg.gpu_url} (--no-tunnel)")
        elif tunnel_alive(cfg) and state.get("node") == node and get_json(transport, f"{cfg.gpu_url}/health"):
            say("PASS", f"reusing the open tunnel to {node}")
        else:
            close_tunnel(cfg)
            open_tunnel(cfg, node, remote_port)
            opened = True
            say("PASS", f"tunnel open: {cfg.gpu_url} -> {node}:{remote_port}")

        try:
            health = get_json(transport, f"{cfg.gpu_url}/health", timeout=15)
            problems = gpu_health_problems(health, course_id=args.course, version=version, min_minutes=args.min_minutes)
            if problems:
                raise Abort("GPU service not ready: " + "; ".join(problems))
            say("PASS", f"GPU service healthy on {health.get('gpuName') or 'GPU'}; decoding = production; "
                        f"{(health.get('secondsRemaining') or 0) / 60:.0f} min left")

            base_model, _, _ = vm_model_names(args.course, version)
            problems = probe_gpu(transport, cfg, course_id=args.course, version=version, base_model=base_model)
            if problems:
                raise Abort("GPU probe failed: " + "; ".join(problems))
            say("PASS", "direct GPU probe: Base and course answers within the classroom cap")

            before = (get_json(transport, f"{cfg.gpu_url}/health") or {}).get("served") or {}
            previous = read_mode_file()[1]
            path = write_mode_file({
                "mode": gm.GPU, "gpuUrl": cfg.gpu_url, "since": now_iso(), "node": node, "jobId": job_id,
                "expiresAt": expires, "courseId": args.course, "modelVersion": version,
                "switchedBy": os.environ.get("USER", ""),
            })
            try:
                mode = backend_mode(session)
                if mode.get("mode") != gm.GPU:
                    raise Abort(f"wrote {path} but the backend reports mode {mode.get('mode')!r} ({mode.get('error')})")
                say("PASS", f"switched: backend now generating on the GPU ({path})")

                problems = four_condition_problems(run_four(session, args.course, cfg.timeout),
                                                   on_gpu=True, course_id=args.course, version=version)
                after = (get_json(transport, f"{cfg.gpu_url}/health") or {}).get("served") or {}
                served = {k: int(after.get(k, 0)) - int(before.get(k, 0)) for k in ("base", "course")}
                if served["base"] < 2 or served["course"] < 2:
                    problems.append(f"the GPU served base +{served['base']}, course +{served['course']} (expected +2 each)")
                if problems:
                    raise Abort("four-condition check in GPU mode failed: " + "; ".join(problems))
                say("PASS", f"all four conditions answered on the GPU (GPU counters: base +{served['base']}, course +{served['course']})")
            except BaseException:
                write_mode_file(previous if previous is not None else {"mode": gm.VM})
                say("FAIL", "restored the previous mode (VM); the backend is generating on the VM again")
                raise
        except BaseException:
            if opened:
                close_tunnel(cfg)
                say("INFO", "closed the tunnel this run opened")
            raise
    finally:
        session.logout()

    print()
    print("CLASSROOM GPU MODE ACTIVE: Base, RAG, Fine-Tuned and Fine-Tuned + RAG are generated on the Tillicum GPU.")
    print(f"  Job {job_id or '?'} on {node} ends {expires or 'at the end of its allocation'}; GPU mode stops working then.")
    print("  Check:   ./scripts/classroom_gpu_mode.sh status")
    print(f"  Revert:  ./scripts/classroom_gpu_mode.sh stop --course {args.course} --admin-email <you> [--cancel-job]")
    return 0


def local_helpers_validate_node(node: str) -> str:
    deploy = _load("finetuned_deploy_helpers", LIB / "finetuned_deploy_helpers.py")
    try:
        return deploy.validate_compute_hostname(node)
    except ValueError as exc:
        raise Abort(f"Invalid compute node hostname {node!r}: {exc}") from exc


def cmd_stop(args: argparse.Namespace, cfg: Config, transport: Any) -> int:
    print("Classroom GPU mode: stop. Switching back to the VM first, then proving it.\n")
    _, _, before = read_mode_file()
    details = before.details if isinstance(before, gm.GenerationMode) else {}
    job_id = str(args.job_id or details.get("jobId") or "")
    write_mode_file({"mode": gm.VM, "since": now_iso(), "switchedBy": os.environ.get("USER", "")})
    say("PASS", "mode file: vm (new requests generate on the VM from now)")

    failures: list[str] = []
    session = sign_in(cfg, args.admin_email, transport, no_auth=args.no_auth)
    try:
        mode = backend_mode(session)
        if mode.get("mode") != gm.VM:
            failures.append(f"backend reports mode {mode.get('mode')!r}")
        else:
            say("PASS", "backend reports VM mode")

        version = args.version or activated_version(session, args.course)
        base_model, tag, ft_ollama = vm_model_names(args.course, version)
        if tag is None:
            failures.append(f"{args.course} {version} is not mapped in {FINETUNED_ENV}")
        else:
            warm = _load("warm_classroom_models", REPO_ROOT / "scripts" / "warm_classroom_models.py")
            print("      Warming the VM models (they may have been unloaded while the GPU served):", flush=True)
            if warm.main(["--base-ollama", cfg.ollama_url, "--base-model", base_model,
                          "--finetuned-ollama", ft_ollama, "--finetuned-model", tag, "--keep-alive", args.keep_alive]) != 0:
                failures.append("warming the VM models failed")
            else:
                say("PASS", "VM models resident")

        ft_health = get_json(transport, f"{cfg.finetuned_url}/health")
        if not ft_health or ft_health.get("status") != "ok":
            failures.append(f"VM fine-tuned service {cfg.finetuned_url} is not healthy")
        problems = four_condition_problems(run_four(session, args.course, cfg.timeout),
                                           on_gpu=False, course_id=args.course, version=version)
        failures += problems
        if not problems:
            say("PASS", "all four conditions answered on the VM")
    finally:
        session.logout()

    if args.cancel_job and job_id and tunnel_alive(cfg):
        if cancel_job(cfg, job_id):
            say("PASS", f"cancelled Tillicum job {job_id}")
            job_id = ""
        else:
            say("WARN", f"could not cancel Tillicum job {job_id}; cancel it by hand")
    closed = close_tunnel(cfg)
    say("PASS" if closed else "INFO", "tunnel closed" if closed else "no tunnel was open")

    print()
    if failures:
        print("VM MODE IS ACTIVE, BUT SOME CHECKS FAILED:")
        for failure in failures:
            print(f"  - {failure}")
    else:
        print("VM MODE ACTIVE: all four conditions are generated on this VM, and verified.")
    if job_id:
        print(f"  REMINDER: Tillicum job {job_id} is still running and using GPU time. On Tillicum: scancel {shlex.quote(job_id)}")
    return 1 if failures else 0


def cmd_status(args: argparse.Namespace, cfg: Config, transport: Any) -> int:
    path, text, mode = read_mode_file()
    print(f"Mode file: {path}" + ("" if text is not None else " (absent: VM mode)"))
    if isinstance(mode, str):
        print(f"MODE: VM (the file is {mode}; the backend ignores it)")
        mode = gm.VM_MODE
    print(f"MODE: {'CLASSROOM GPU' if mode.is_gpu else 'VM (normal)'}")
    for key, value in (mode.details or {}).items():
        print(f"  {key}: {value}")

    alive = tunnel_alive(cfg)
    state = read_tunnel_state(cfg)
    health = get_json(transport, f"{cfg.gpu_url}/health") if alive or mode.is_gpu else None
    print(f"\nTunnel: {'open to ' + str(state.get('node')) if alive else 'closed'} ({cfg.gpu_url})")
    if health:
        remaining = health.get("secondsRemaining")
        print(f"  GPU service: {health.get('status')} on {health.get('gpuName') or '?'}, "
              f"{'%.0f min left' % (remaining / 60) if isinstance(remaining, (int, float)) else 'time left unknown'}, "
              f"adapters {health.get('loadedAdapters')}, served {health.get('served')}")

    base_model, _, ft_ollama = vm_model_names(mode.details.get("courseId", ""), mode.details.get("modelVersion", ""))
    rows = gm.describe(mode, ollama_url=cfg.ollama_url, ollama_model=base_model, finetuned_url=cfg.finetuned_url)["routes"]
    print("\nWhere each condition is generated:")
    for condition in CONDITIONS:
        print(f"  {condition:13} {rows[condition]}")

    print("\nVM services (ready for VM mode):")
    print(f"  backend      {'ok' if get_json(transport, cfg.backend_url + '/api/health') else 'DOWN'} ({cfg.backend_url})")
    ft = get_json(transport, cfg.finetuned_url + "/health")
    print(f"  fine-tuned   {(ft or {}).get('status', 'DOWN')} ({cfg.finetuned_url} -> {(ft or {}).get('ollamaUrl', '?')})")
    for url in dict.fromkeys([cfg.ollama_url, ft_ollama]):
        ps = get_json(transport, url + "/api/ps")
        names = [m.get("name") for m in (ps or {}).get("models") or []]
        print(f"  ollama       {url}: {'resident ' + ', '.join(names) if names else ('nothing resident' if ps is not None else 'DOWN')}")

    problems = []
    if mode.is_gpu and not health:
        problems.append("GPU MODE IS ON BUT THE GPU SERVICE IS UNREACHABLE: students get errors. Run: ./scripts/classroom_gpu_mode.sh stop ...")
    if mode.is_gpu and health and isinstance(health.get("secondsRemaining"), (int, float)) and health["secondsRemaining"] < 900:
        problems.append("the GPU allocation ends within 15 minutes: plan to run `stop`")
    if not mode.is_gpu and alive:
        problems.append("VM mode, but the GPU tunnel is still open (and the Tillicum job may still be running)")

    if args.verify:
        session = sign_in(cfg, args.admin_email, transport, no_auth=args.no_auth)
        try:
            seen = backend_mode(session)
        finally:
            session.logout()
        agree = seen.get("mode") == mode.kind
        print(f"\nBackend reports: {seen.get('mode')} {'(agrees with the file)' if agree else '(DISAGREES with the file)'}")
        if not agree:
            problems.append("the backend and the mode file disagree")

    for problem in problems:
        print(f"\nWARNING: {problem}")
    return 1 if problems else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("start", "stop", "status"):
        p = sub.add_parser(name)
        p.add_argument("--admin-email", help=f"Administrator sign-in (password from ${checks.PASSWORD_ENV} or a prompt).")
        p.add_argument("--backend-url", default=checks.DEFAULT_BACKEND_URL)
        p.add_argument("--gpu-port", type=int, default=int(os.environ.get("GPU_MODE_LOCAL_PORT") or DEFAULT_GPU_PORT))
        p.add_argument("--timeout", type=float, default=180.0)
        p.add_argument("--no-auth", action="store_true", help=argparse.SUPPRESS)
        if name in ("start", "stop"):
            p.add_argument("--course", required=True, help="The course being taught, e.g. css360e-autumn-2026-c08m.")
            p.add_argument("--version", help="Override the activated version (default: read from the backend).")
        if name == "start":
            p.add_argument("--node", help="Compute node, instead of the recorded serving session.")
            p.add_argument("--remote-port", type=int, default=DEFAULT_REMOTE_PORT)
            p.add_argument("--job-id", help="Slurm job id, with --node.")
            p.add_argument("--no-tunnel", action="store_true",
                           help="Use a forward already open on --gpu-port (opened by hand) instead of opening one.")
            p.add_argument("--min-minutes", type=float, default=DEFAULT_MIN_MINUTES,
                           help="Refuse a session with less time left than this (default %(default)s).")
        if name == "stop":
            p.add_argument("--cancel-job", action="store_true", help="scancel the Tillicum job through the open tunnel.")
            p.add_argument("--job-id", help="The Slurm job to cancel (default: the one GPU mode recorded).")
            p.add_argument("--keep-alive", default="4h", help="keep_alive for the warmed VM models (default %(default)s).")
        if name == "status":
            p.add_argument("--verify", action="store_true", help="Also ask the backend (needs --admin-email).")
    return parser


def main(argv: list[str] | None = None, *, transport: Any = None) -> int:
    args = build_parser().parse_args(argv)
    cfg = Config(backend_url=args.backend_url.rstrip("/"), gpu_port=args.gpu_port, timeout=args.timeout)
    transport = transport or checks.Transport()
    command = {"start": cmd_start, "stop": cmd_stop, "status": cmd_status}[args.command]
    try:
        return command(args, cfg, transport)
    except Abort as exc:
        print(f"\nFAIL  {exc}", file=sys.stderr)
        if args.command == "start":
            print("The backend is in VM mode; nothing was left half-switched.", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
